[metadata]
name = "Islands Dark"
author = "Neovim port of bwya77/vscode-dark-islands"

[colors]
foreground = "#bcbec4"
background = "#181a1d"
cursor_bg = "#bcbec4"
cursor_fg = "#181a1d"
cursor_border = "#bcbec4"
selection_fg = "#bcbec4"
selection_bg = "#373b39"
scrollbar_thumb = "#7a7e85"
split = "#161619"
compose_cursor = "#73b00a"
visual_bell = "#373b39"
ansi = ["#181a1d", "#f75464", "#73b00a", "#e8a33e", "#548af7", "#c77dbb", "#2aacb8", "#bcbec4"]
brights = ["#6f737a", "#f9667a", "#8ccf15", "#f0b95e", "#7cacf8", "#d79fd2", "#42c6d2", "#d4d5d9"]

[colors.tab_bar]
background = "#161619"

[colors.tab_bar.active_tab]
bg_color = "#181a1d"
fg_color = "#bcbec4"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
bg_color = "#161619"
fg_color = "#7a7e85"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#161619"
fg_color = "#b0b2b8"
italic = true

[colors.tab_bar.new_tab]
bg_color = "#161619"
fg_color = "#7a7e85"

[colors.tab_bar.new_tab_hover]
bg_color = "#373b39"
fg_color = "#bcbec4"
