require("items.widgets.battery")
require("items.widgets.volume")
require("items.widgets.vpn")
require("items.widgets.wifi")
require("items.widgets.ram")
require("items.widgets.gpu")
require("items.widgets.cpu")
