tmux:
  styles:
    clear: "#[fg=colour245]"
    state: "#[fg=colour196,bold]"
    branch: "#[fg=colour255,bold]"
    remote: "#[fg=colour80]"
    divergence: "#[fg=colour245]"
    staged: "#[fg=colour150,bold]"
    conflict: "#[fg=colour196,bold]"
    modified: "#[fg=colour221,bold]"
    untracked: "#[fg=colour141,bold]"
    stashed: "#[fg=colour111,bold]"
    clean: "#[fg=colour224,bold]"
    insertions: "#[fg=colour150]"
    deletions: "#[fg=colour196]"
