# vim:set ft=tmux:
%hidden MODULE_NAME="battery"
set -gq @catppuccin_battery_icon "󰂄 "
set -gq @catppuccin_battery_color "#95E1D3"
set -gq @catppuccin_battery_text " #($HOME/.config/tmux/plugins/tmux-battery/scripts/battery_percentage.sh)"
set -gqF "@catppuccin_status_${MODULE_NAME}_icon_bg" "#{@catppuccin_${MODULE_NAME}_color}"
set -gqF "@catppuccin_status_${MODULE_NAME}_text_fg" "#{E:@thm_fg}"
set -gqF "@catppuccin_status_${MODULE_NAME}_text_bg" "#{E:@catppuccin_status_module_text_bg}"
set -gqF @catppuccin_status_middle_separator "#[fg=#{@catppuccin_status_${MODULE_NAME}_icon_bg},bg=#{@catppuccin_status_${MODULE_NAME}_text_bg}]"
source-file -F "#{TMUX_PLUGIN_MANAGER_PATH}tmux/utils/status_module.conf"
