# vim:set ft=tmux:
%hidden MODULE_NAME="network"
set -gq @catppuccin_network_icon "󰛳 "
set -gq @catppuccin_network_color "#EAFFD0"
set -gq @catppuccin_network_text " ↑ #($HOME/.config/tmux/status_pills/scripts/net_rate.sh up) ↓ #($HOME/.config/tmux/status_pills/scripts/net_rate.sh down)"
set -gqF "@catppuccin_status_${MODULE_NAME}_text_fg" "#{E:@thm_fg}"
set -gqF "@catppuccin_status_${MODULE_NAME}_text_bg" "#{E:@catppuccin_status_module_text_bg}"
set -gqF @catppuccin_status_middle_separator "#[fg=#{@catppuccin_status_${MODULE_NAME}_icon_bg},bg=#{@catppuccin_status_${MODULE_NAME}_text_bg}]"
source-file -F "#{TMUX_PLUGIN_MANAGER_PATH}tmux/utils/status_module.conf"
